#ifndef LSLINKS_COMMON_H__
#define LSLINKS_COMMON_H__

#define LSLINKS_VERSION_MAJOR 1
#define LSLINKS_VERSION_MINOR 0
#define LSLINKS_VERSION_PATCH 0
#define LSLINKS_STR_(S) #S
#define LSLINKS_STR(S) LSLINKS_STR_(S)
#define LSLINKS_VERSION LSLINKS_STR(LSLINKS_VERSION_MAJOR) "." LSLINKS_STR(LSLINKS_VERSION_MINOR) "." LSLINKS_STR(LSLINKS_VERSION_PATCH)

#include <stdbool.h>

#endif // LSLINKS_COMMON_H__
